### ISSUE TITLE
React Portal

### ISSUE THREAD

**Issue by lalitkapoor** [TeemuKoivisto/prosemirror-react-typescript-example#4]
I wonder if the reason React Portal isn't working is because of this https://github.com/facebook/react/issues/12653

**Comment by TeemuKoivisto** [comment]
Hey @lalitkapoor, I have fixed the rendering issue with portals. The link you provided was indeed relevant although there was various other moving parts that needed also to be addressed. Apologies for taking this long to answer 😅 .

Yet as I have researched this topic, mainly by examining the other PM-React editors out there, I have found that using portals might not actually be preferable due to some React's async vs ProseMirror's sync rendering issues.

https://bitbucket.org/atlassian/atlaskit-mk-2/commits/d520a6fb6dab1027d3873eec9317c4e8574d07fb

Idk. Will have to research that later on if problems arise. Now I'm just trying to complete the `full` editor.

**Comment by TeemuKoivisto** [comment]
@lalitkapoor I think I have now fixed the portals to the best of my ability as possible. The portals are rendered only once per `dispatchTransaction` which should avoid a performance bottleneck with too many nodeViews firing updates in one transaction. But from what I can tell from the flame graphs I think the biggest bottle neck is now React itself as it is not maybe that suitable for rendering multiple small components vs one big tree. I have been thinking about implementing the example editor in Svelte to see how much better it is but time will tell.
